### ISSUE TITLE
still too much white space on articles

### ISSUE THREAD

**Issue by daguilarc** [sfyimby/sfyimby#20]
see attachment
![whitespacefail](https://cloud.githubusercontent.com/assets/12903137/18534801/98d9bdc4-7aa3-11e6-8250-44f1f6a84aec.jpg)

**Comment by daguilarc** [comment]
hi this still needs to be fixed

**Comment by bufordsharkley** [comment]
This is exacerbated by the left-justification of the banner image.

Really, the banner image should probably have responsive rules for
expanding and becoming a more reasonable size on desktop (Bootstrap has
functionality like this, I'm pretty sure...)

**Comment by ErikGoldman** [comment]
the issue is that in order to make the image wider + maintain the aspect ratio, we also have to make it taller.

that'll make images look something like this

![screenshot 2016-09-15 21 51 33](https://cloud.githubusercontent.com/assets/243490/18575620/a7d1acc4-7b8e-11e6-9635-8bb35a2bbcac.png)

is that reasonable? I can do it if that's not too tall for you guys.

**Comment by daguilarc** [comment]
Looks fine to me. Thanks!

**Comment by ErikGoldman** [comment]
done!
